Repository NIAEFEUP/uni, pull requests merged in 2025-04, with the labels that each got.

#1541 Delete old schedule page and its tests
  packages/uni_app/lib/main.dart
  packages/uni_app/lib/utils/navigation_items.dart
  packages/uni_app/lib/view/schedule/schedule.dart
  packages/uni_app/lib/view/schedule/widgets/schedule_slot.dart
  packages/uni_app/test/unit/view/Pages/schedule_page_view_test.dart
  packages/uni_app/test/unit/view/Widgets/schedule_slot_test.dart
Labels: redesign

#1543 Delete old course units page and widgets
  packages/uni_app/lib/main.dart
  packages/uni_app/lib/utils/navigation_items.dart
  packages/uni_app/lib/view/academic_path/widgets/course_units_card.dart
  packages/uni_app/lib/view/course_units/course_units.dart
  packages/uni_app/lib/view/course_units/widgets/course_unit_card.dart
Labels: redesign

#1549 Added redirect to respective course unit on schedule/exam card click.
  packages/uni_app/lib/view/academic_path/academic_path.dart
  packages/uni_app/lib/view/academic_path/exam_page.dart
  packages/uni_app/lib/view/academic_path/widgets/schedule_day_timeline.dart
  packages/uni_app/lib/view/home/home.dart
  packages/uni_app/lib/view/home/widgets/calendar/calendar_home_card.dart
  packages/uni_app/lib/view/home/widgets/exams/exam_home_card.dart
  packages/uni_app/lib/view/home/widgets/generic_home_card.dart
  packages/uni_app/lib/view/home/widgets/library/library_home_card.dart
  packages/uni_app/lib/view/home/widgets/restaurants/restaurant_home_card.dart
  packages/uni_app/lib/view/home/widgets/schedule/schedule_home_card.dart
  packages/uni_ui/lib/cards/exam_card.dart
  packages/uni_ui/lib/cards/schedule_card.dart
Labels: enhancement, redesign

#1547 Pages smooth transition
  packages/uni_app/lib/main.dart
  packages/uni_app/lib/utils/navigation_items.dart
  packages/uni_app/lib/view/academic_path/widgets/course_units_view.dart
  packages/uni_app/lib/view/home/edit_home.dart
  packages/uni_app/lib/view/lazy_consumer.dart
  packages/uni_app/lib/view/profile/widgets/settings.dart
Labels: redesign

#1585 Fixed status bar icon brightness on the home screen.
  packages/uni_app/lib/main.dart
  packages/uni_app/lib/view/home/edit_home.dart
  packages/uni_app/lib/view/home/home.dart
Labels: bug

#1596 fix: dragging in homepage edit
  flake.lock
  flake.nix
  packages/uni_app/lib/controller/local_storage/preferences_controller.dart
  packages/uni_app/lib/view/home/edit_home.dart
  packages/uni_app/lib/view/home/widgets/edit/draggable_element.dart
  packages/uni_app/lib/view/home/widgets/edit/draggable_square.dart
  packages/uni_app/lib/view/home/widgets/edit/draggable_tile.dart
  packages/uni_app/lib/view/home/widgets/edit/draggable_utils.dart
Labels: bug

#1595 Fix NoSQL lecture bug
  packages/uni_app/lib/generated/model/entities/lecture.g.dart
  packages/uni_app/lib/model/entities/lecture.dart
  packages/uni_app/lib/objectbox-model.json
  packages/uni_app/lib/objectbox.g.dart
Labels: bug
